project:
  type: website

website:
  title: "Daniel Sánchez-García"
  favicon: img/network.png
  navbar:
    background: lightgrey
    foreground: black
    search: false
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd  
      - publications.qmd
      - cv.qmd
      - gallery.qmd
      - contact.qmd
  reader-mode: true
  
  page-footer: 
    left: |
      {{< fa regular copyright >}} Daniel Sanchez-Garcia, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

